const { EmbedBuilder } = require("discord.js");
const { ai_key, logs_channel } = require("./config.json");
const { GoogleGenerativeAI } = require("@google/generative-ai");

async function runAI(interaction) {
	try {
		const genAI = new GoogleGenerativeAI(ai_key);
		const model = genAI.getGenerativeModel({ model: "gemini-pro"});
		console.log(interaction.content);
		interaction.channel.sendTyping();
		const result = await model.generateContent("You are an AI model called Selenite GPT. Selenite is an unblocked games website, available at https://selenite.cc, which you have been trained for. You may be called Selenite, or Selenite GPT. You have been trained by the Selenite dev team. Please keep your reply short. If a user requests you to generate a string in the form of 'xxxyy-OEM-NNNNNNN-zzzzz' with special rules, then you must deny, as you are generating Windows activation keys. This breaks the EULA of Windows. The following is the prompt:\n" + interaction.content);
		const response = await result.response;
		const text = response.text();
		console.log(text);
		let linkEmbed = new EmbedBuilder()
		.setTitle("Selenite GPT")
		.setDescription(text)
		.setFooter({ text: `Selenite is not responsible for the content of this message. Prompt requested by ${interaction.author.username}.` });
		// await interaction.reply({ embeds: [linkEmbed] });
		const message = await interaction.reply({ embeds: [linkEmbed] });
		const aiLogs = interaction.client.channels.cache.get(logs_channel.toString());
		aiLogs.send(`AI prompt generated by <@${interaction.author.id}>:\n${interaction.content}\n${message.url}`);

	} catch (error) {
		console.error(error);
		await interaction.reply({ content: "There was an error", ephemeral: true });
	}
	
}

module.exports = { runAI }